spring.application.name=empresa-transportista-efs
server.port=8080

# Bucket S3 (configurar con el nombre de tu bucket en AWS)
aws.s3.bucket=${AWS_S3_BUCKET:tu-bucket-guias}

# Configuracion EFS
efs.path=${EFS_PATH:/app/efs}

# Logs AWS (util para depuracion en EC2)
logging.level.software.amazon.awssdk=DEBUG
logging.level.io.awspring.cloud=DEBUG

# Perfil de produccion: EFS montado en /app/efs via Docker (-v /home/ec2-user/efs:/app/efs)

# Azure AD B2C - validacion JWT (Resource Server)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://empresatransportistaefs.b2clogin.com/972f25cf-cd03-4c70-84ea-285778b48398/v2.0/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://empresatransportistaefs.b2clogin.com/empresatransportistaefs.onmicrosoft.com/B2C_1_cdy2204-1/discovery/v2.0/keys
